version: '3.4'

services:
  backend:
    image: spidernets.azurecr.io/spidernets-backend:latest
    ports:
      - "8000"
    container_name: backend
    restart: always

  frontend:
    image: spidernets.azurecr.io/spidernets-frontend:latest
    ports:
      - "3000:80" 
    container_name: frontend
    restart: always