services:
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/root/ssl/cert.pem
      - ./key.pem:/root/ssl/key.pem
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - frontend
    networks:
      - spidernets

  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    image: spidernets-backend
    restart: always
    entrypoint:
      [
        "bash",
        "-c",
        "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000",
      ]
    networks:
      - spidernets

  frontend:
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    image: spidernets-frontend
    restart: always
    networks:
      - spidernets

networks:
  spidernets:
